Sparkle/Models/Post/AddCommentViewModel.cs
using System;

namespace Sparkle.Models
{
    public class AddCommentViewModel
    {
        public string Body { get; set; }

        public string PostId { get; set; }

        public string OwnerName { get; set; }
        public string OwnerSurname { get; set; }
        public string OwnerUserName { get; set; }
        public DateTime Created { get; set; } = DateTime.Now;

    }
}

Sparkle/Models/Post/PostRenderViewModel.cs
using System.Collections.Generic;
using System.Security.Claims;

namespace Sparkle.Models.Post
{
    public class PostRenderViewModel
    {
        public ClaimsPrincipal User { get; set; }

        public IEnumerable<Domain.Entities.Post> Posts { get; set; }

        public string TypeOfRender { get; set; }
    }
}

Sparkle/Models/Post/PostViewModel.cs
using Sparkle.Domain.Entities;

namespace Sparkle.Models
{
    public class PostViewModel
    {
        public Domain.Entities.Post Post { get; set; }

        public User User { get; set; }
    }
}

Sparkle/Controllers/FriendController.cs
using Microsoft.AspNetCore.Mvc;
using Sparkle.Domain.Entities;
using Sparkle.Domain.Services;
using Sparkle.Models;
using Sparkle.Neo4j.Domain.Services;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sparkle.Controllers
{
    public class FriendController : Controller
    {
        #region Private Members
        private readonly UserService _userService;
        private readonly PostService _postService;
        private readonly FriendService _friendService;
        private readonly GraphUserService _graphService;
        #endregion

        #region Constructor

        public FriendController(UserService userService, PostService postService, GraphUserService graphService)
        {
            _userService = userService;
            _postService = postService;
            _friendService = new FriendService(_userService);
            _graphService = graphService;
        }

        #endregion

        #region Action Methods


        [HttpGet]
        [Route("/Friends")]
        public async Task<IActionResult> Friends()
        {
            var model = new FriendsListViewModel
            {
                User = await _userService.GetAsync(User),
                Friends = (List<Friend>)(_userService.GetFriends(User.Identity.Name))
            };
            return View(model);
        }

        [HttpGet]
        [Route("/Profile/{userName}")]
        public async Task<IActionResult> Profile(string userName)
        {
            if (userName == User.Identity.Name)
                return RedirectToAction("Profile", "Home");

            var model = new UserProfileViewModel
            {
                User = await _userService.GetByUserNameAsync(userName),

            };
            model.PathBetween = _graphService.PathLengthBetween(_userService.GetByUserName(User.Identity.Name), model.User);
            model.Posts = (await _postService.GetAsync()).Where(p => p.OwnerUserName == model.User.UserName);
            return View(model);
        }

        #endregion

        #region Helper Methods

        [HttpGet]
        [Route("/AddFriend")]
        public async Task AddFriend(string Id)
        {
            await _friendService.AddAsync(User, Id);
        }

        #endregion

    }
}

Sparkle/Controllers/PostController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sparkle.Domain.Entities;
using Sparkle.Domain.Services;
using Sparkle.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Sparkle.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class PostController : Controller
    {
        #region Private Members
        private readonly PostService _postService;
        private readonly UserService _userService;
        private readonly CommentService _commentService;
        #endregion

        public PostController(PostService postService, UserService userService, CommentService commentService)
        {
            _postService = postService;
            _userService = userService;
            _commentService = commentService;
        }


        [HttpGet]
        [Route("Post/{postId}")]
        public async Task<IActionResult> Index(string postId)
        {
            var viewModel = new PostViewModel()
            {
                Post = await _postService.GetAsync(postId),
                User = await _userService.GetByUserNameAsync(User.Identity.Name)
            };
            return View(viewModel);
        }

        [HttpPost]
        [Route("/AddComment")]
        public async Task<PartialViewResult> AddComment(string postId, AddCommentViewModel model)
        {
            var comment = new Comment()
            {
                Body = model.Body,
                CreatedDate = DateTime.Now,
                OwnerName = model.OwnerName,
                OwnerSurname = model.OwnerSurname,
                OwnerUserName = model.OwnerUserName
            };
            await _commentService.AddCommentAsync(postId, comment);
            return PartialView("NewComment", comment);
        }


        #region Helper Methods

        [HttpPost]
        [Route("Post/RemovePost/{postId}")]
        public async Task<IActionResult> RemovePost(string postId)
        {
            await _postService.RemoveAsync(postId);

            return RedirectToAction("Index", "Home");
        }


        #endregion


    }
}

Sparkle/ViewComponents/MiniCommentViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Sparkle.Domain.Entities;
using System.Threading.Tasks;

namespace Sparkle.ViewComponents
{
    public class MiniCommentViewComponent : ViewComponent
    {

        public async Task<IViewComponentResult> InvokeAsync(Comment comment)
        {
            return View(comment);
        }
    }
}

Sparkle/Views/Shared/Post.cshtml
@model IEnumerable<Post>
@{
    foreach (var post in Model)
    {
        <div class="post">
            <h3 class="post__title">
                <a asp-action="Profile" asp-controller="Friend" asp-route-userName="@post.OwnerUserName">@post.CreatedBy</a>
            </h3>
            <a asp-action="Index" asp-controller="Post" asp-route-postId="@post.Id">
                <div class="post__body">@post.Body</div>
            </a>
            <div class="post__created-time">@post.CreatedDate.ToString("dd/MM/yyyy HH:mm")</div>
            <form>
                <input type="hidden" name="id" value="@post.Id" />
                @if (post.Likes == null || post.Likes.Count == 0)
                {
                    <button type="button" class="post__like">
                        <span>&hearts;</span> <span class="counter">0</span>
                    </button>
                }
                else
                {
                    @if (post.Likes.Any(l => l.OwnerUsername == User.Identity.Name))
                    {
                        <button type="button" class="post__like liked">
                            <span>&hearts;</span>

                            <span class="counter">
                                @post.Likes.Count
                            </span>
                        </button>
                    }
                    else
                    {
                        <button type="button" class="post__like">
                            <span>&hearts;</span>

                            <span class="counter">
                                @post.Likes.Count
                            </span>
                        </button>
                    }
                }
            </form>
            @if (post.Comments == null || post.Comments.Count == 0)
            {
                <button class="post__comment"><img src="https://img.icons8.com/ios/50/000000/comments.png"> 0</button>
            }
            else
            {
                <button class="post__comment"><img src="https://img.icons8.com/ios/50/000000/comments.png"> @post.Comments.Count</button>
            }
            @if (post.Comments != null && post.Comments.Count != 0)
            {
                <div class="separator"></div>
                <div class="mini-comment-container">
                    @for (int i = 0; i < post.Comments.Count && i < 2; i++)
                    {
                        @await Component.InvokeAsync("MiniComment", post.Comments.OrderByDescending(x => x.CreatedDate).ToList()[i]);
                    }
                </div>
            }
        </div>
    }
}

Sparkle/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sparkle</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" type="text/css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <header class="header">
            <div class="header__logo logo">
                <a asp-controller="Home" asp-action="Index"><img class="logo__img" src="~/img/logo.png" /></a>
            </div>
            <div class="header__search search">
                <form asp-action="Search" asp-controller="Search">
                    <input type="text" name="searchString" class="search__box search_border_none" />
                    <input type="submit" id="search-btn" class="search__button search_border_none"  value="Search" />
                </form>
            </div>

            @if (User.Identity.IsAuthenticated)
            {
                <div class="header__sign-out sign-out">
                    <a class="sign-out__button" asp-controller="Account" asp-action="Logout">Sing out</a>
                </div>
            }

        </header>
        <nav class="nav">
            <a asp-action="Profile" asp-controller="Home" class="nav__link">My page</a>
            <a asp-action="Index" asp-controller="Home" class="nav__link">News</a>
            <a asp-action="Friends" asp-controller="Friend" class="nav__link">Friends</a>
        </nav>
        <div class="content">
            @RenderBody()
        </div>
        <footer class="footer">
            &copy; @DateTime.Now.Year
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Sparkle/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_LoginLayout</title>
    <link href="~/css/login.css" rel="stylesheet" asp-append-version="true"/>
</head>
<body>
    <div class="container">
        <header class="header">
            <div class="header__logo logo">
                <a asp-controller="Home" asp-action="Index"><img class="logo__img" src="~/img/logo.png" /></a>
            </div>
            <div class="header__title title">
                Sparkle
            </div>
        </header>
        <div class="content">
            @RenderBody()
        </div>
    </div>

</body>
</html>